name: The Lending Blog
description: Thoughts on peer-to-peer margin lending by
meta_description: "Thoughts on peer-to-peer margin lending by Poloniexlendingbot.com"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-75870022-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog.poloniexlendingbot.com'
author:         'Poloniexlendingbot.com'
