name: Poloniex Lending Bot
description: Blog for the Poloniexlendingbot.com service.
meta_description: "Blog for the Poloniexlendingbot.com service."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-75870022-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog.poloniexlendingbot.com'
author:         'Ben'
